name: Android Push Master CI

on:
  push:
    branches:
      - 'master'
jobs:
  test: # Job of ID test
    name: Run Unit Tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Step 1 - set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Step 2 - Units Test
        run: bash ./gradlew test --stacktrace
  apk:
    name: Generate APK
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Step 1 - set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Step 2 - Build debug APK
        run: bash ./gradle assembleDebug --stacktrace
      - name: Step 3 - Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk

